# -*- coding: utf-8 -*-
"""TÉCNICOS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oHQM5UqWsLCK79CH_ahRDuujUuErgUHk
"""

# pip install yfinance pandas numpy matplotlib ta mplfinance

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import yfinance as yf
import seaborn as sns
import networkx as nx
import community as community_louvain
from networkx.algorithms.community import girvan_newman
import statsmodels.api as sm
from statsmodels.tsa.stattools import coint
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import plotly.graph_objects as go
from collections import Counter
import openpyxl
import os
from scipy.optimize import minimize
from datetime import datetime, timedelta
from scipy.stats import skew, kurtosis
from matplotlib.colors import LinearSegmentedColormap
from statsmodels.tsa.seasonal import seasonal_decompose
from ta.trend import SMAIndicator, MACD, IchimokuIndicator
from ta.momentum import RSIIndicator

# CELDA 1: instalar (si es necesario) e importar
#!pip install yfinance --quiet
#!pip install ta mplfinance --quiet


import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from IPython.display import Image, display
import os, glob

plt.style.use('dark_background')
rc = {
    'axes.facecolor':   '#222222',
    'figure.facecolor':'#222222',
    'axes.edgecolor':   '#444444',
    'grid.color':       '#333333',
    'xtick.color':      'white',
    'ytick.color':      'white',
}
plt.rcParams.update(rc)

# Parámetros
tickers = [
    "AA1.MX",
    "ACTINVRB.MX",
    "AMXB.MX",
    "BABAN.MX",
    "BBAJIOO.MX",
    "CVS.MX",
    "FUBO.MX",
    "GM.MX",
    "GRUMAB.MX",
    "MARA.MX",
    "MFRISCOA-1.MX",
    "NVAX.MX",
    "ORBIA.MX",
    "PINFRA.MX",
    "RIOT.MX",
    "VOLARA.MX",
    "NVDA.MX"
]
end_date = "2025-09-28"   # fecha final "YYYY-MM-DD"
years_for_seasonality = 1
period = 'D'   # 'D' diario o 'W' semanal (si quieres semanal cambia más abajo)
output_folder = "plots_step"
os.makedirs(output_folder, exist_ok=True)

# Tamaño del test para la GRAFICA 2 (en días)
test_size_days = 60

# CELDA 2: descargar por ticker (OHLCV) y guardar en dict
from datetime import datetime
end = pd.to_datetime(end_date)
start = end - pd.DateOffset(years=years_for_seasonality)

data_dict = {}
errors = {}

for t in tickers:
    try:
        print("Descargando:", t)
        df = yf.download(t, start=start.strftime("%Y-%m-%d"), end=(end + pd.Timedelta(days=1)).strftime("%Y-%m-%d"), progress=False, auto_adjust=False)
        if df.empty:
            print("  -> Sin datos para", t)
            errors[t] = "no data"
            continue
        # mantener OHLCV
        df = df[['Open','High','Low','Close','Volume']].ffill().dropna()
        # opcional: resample semanal si quieres
        if period == 'W':
            df = df.resample('W-FRI').agg({'Open':'first','High':'max','Low':'min','Close':'last','Volume':'sum'}).dropna()
        data_dict[t] = df
        print(f"  -> OK {df.shape[0]} filas")
    except Exception as e:
        print("  Error", t, e)
        errors[t] = str(e)

print("Descarga completa. errores:", errors)

# CELDA 3 (modificada): SOLO gráficos de precio (Close) por ticker
for t, df in data_dict.items():
    df_plot = df.copy()
    if 'Close' not in df_plot.columns or df_plot['Close'].dropna().shape[0] < 3:
        print(f"{t}: no hay suficiente data de Close ({df_plot.shape[0]} filas). Saltando.")
        continue

    series = df_plot['Close'].copy()

    plt.figure(figsize=(16,6))
    plt.plot(series.index, series.values, linewidth=1.6, alpha=0.95)
    plt.title(f"{t} — Precio de cierre (Close) — {period}")
    plt.xlabel("Fecha")
    plt.ylabel("Precio Close")
    plt.grid(True)
    plt.tight_layout()

    outp = f"{output_folder}/{t.replace('.','_')}_price_only.png"
    plt.savefig(outp, dpi=150, bbox_inches='tight')
    plt.show()
    plt.close()
    print("Guardado:", outp)

# CELDA: Normalizar MultiIndex -> forzar 1-D -> calcular indicadores y plot (robusto)
#!pip install mplfinance ta --quiet

import pandas as pd
import numpy as np
import mplfinance as mpf
from IPython.display import Image, display
from ta.trend import SMAIndicator, MACD, IchimokuIndicator
from ta.momentum import RSIIndicator
import os
os.makedirs(output_folder, exist_ok=True)

# Parámetros
sma_short, sma_med, sma_long = 10, 50, 200
rsi_window = 14

def flatten_columns_if_multiindex(df):
    """
    Si df.columns es MultiIndex intenta reducirlo a un Index simple conteniendo
    'Open','High','Low','Close','Volume' si es posible. Si no, aplana uniendo niveles.
    """
    if not isinstance(df.columns, pd.MultiIndex):
        return df

    lvl_values = [set(df.columns.get_level_values(i)) for i in range(df.columns.nlevels)]
    needed = {'Open','High','Low','Close','Volume'}

    # Si algún nivel contiene las etiquetas necesarias, usamos ese nivel
    for i, s in enumerate(lvl_values):
        if needed.issubset(s):
            df.columns = df.columns.get_level_values(i)
            return df

    # Si no hay nivel claro, intentamos tomar el último nivel (frecuente en yfinance)
    last = df.columns.get_level_values(-1)
    if needed.issubset(set(last)):
        df.columns = last
        return df

    # Fallback: construir nombres 'level0_level1_...'
    df.columns = ['_'.join([str(x) for x in col if x is not None and str(x) != '']) for col in df.columns]
    return df

def to_1d_series(x, index, name):
    """Devuelve pd.Series 1-D con índice `index` y dtype float."""
    if isinstance(x, pd.DataFrame):
        if x.shape[1] == 1:
            arr = x.iloc[:,0].values
        else:
            arr = x.iloc[:,0].values  # fallback: tomar primera columna
    elif isinstance(x, pd.Series):
        arr = x.values
    else:
        arr = np.asarray(x)
    arr = arr.ravel()
    s = pd.Series(arr, index=index, name=name)
    s = pd.to_numeric(s.astype(object), errors='coerce').astype(float)
    return s

# Recorremos data_dict y procesamos cada ticker
for ticker, df in list(data_dict.items()):
    try:
        print("Procesando:", ticker)
        if df is None or df.empty:
            print("  -> sin datos, salto.")
            continue

        df = df.copy()
        df.index = pd.to_datetime(df.index)
        df.sort_index(inplace=True)

        # 1) Normalizar columnas si son MultiIndex o si las etiquetas están en niveles
        df = flatten_columns_if_multiindex(df)

        # 2) Intentar renombrar columnas si vienen con prefijos (ej. 'Price_Open' etc)
        #    Buscamos las columnas que contengan 'Open','High','Low','Close','Volume' en su nombre.
        cols_lower = {c: c.lower() for c in df.columns}
        mapping = {}
        for wanted in ['open','high','low','close','volume']:
            # buscar una columna cuyo nombre (minusculas) sea exactamente wanted, o la contenga
            found = None
            for c, cl in cols_lower.items():
                if cl == wanted:
                    found = c; break
            if found is None:
                for c, cl in cols_lower.items():
                    if wanted in cl:
                        found = c; break
            if found:
                mapping[found] = wanted.capitalize()  # mapeamos a 'Open','High',...
        if mapping:
            df = df.rename(columns=mapping)

        # 3) Verificación final: deben existir las 5 columnas OHLCV
        required = ['Open','High','Low','Close','Volume']
        missing = [c for c in required if c not in df.columns]
        if missing:
            raise KeyError(missing)

        # 4) Forzar cada columna a Series 1-D float
        for c in required:
            df[c] = to_1d_series(df[c] if not isinstance(df[c], pd.DataFrame) else df[[c]], df.index, c)

        # 5) Eliminar filas con OHLC incompleto
        before = len(df)
        df.dropna(subset=['Open','High','Low','Close'], inplace=True)
        after = len(df)
        if after == 0:
            print("  -> no quedan filas tras dropna(OHLC), salto.")
            continue
        if after < before:
            print(f"  -> eliminadas {before-after} filas por OHLC incompleto. Restan {after} filas")

        # 6) Asegurar float
        df[['Open','High','Low','Close','Volume']] = df[['Open','High','Low','Close','Volume']].astype(float)

        # 7) Crear variables 1-D para ta
        close = pd.Series(df['Close'].values.ravel(), index=df.index, name='Close')
        high  = pd.Series(df['High'].values.ravel(), index=df.index, name='High')
        low   = pd.Series(df['Low'].values.ravel(), index=df.index, name='Low')

        # 8) Calcular indicadores con entradas 1-D
        df[f"SMA_{sma_short}"] = SMAIndicator(close, window=sma_short).sma_indicator()
        df[f"SMA_{sma_med}"]   = SMAIndicator(close, window=sma_med).sma_indicator()
        df[f"SMA_{sma_long}"]  = SMAIndicator(close, window=sma_long).sma_indicator()

        macd = MACD(close, window_slow=26, window_fast=12, window_sign=9)
        df["MACD"]        = macd.macd()
        df["MACD_signal"] = macd.macd_signal()
        df["MACD_diff"]   = macd.macd_diff()

        df["RSI"] = RSIIndicator(close, window=rsi_window).rsi()

        ichi = IchimokuIndicator(high=high, low=low, window1=9, window2=26, window3=52)
        df["ichimoku_conv"] = ichi.ichimoku_conversion_line()
        df["ichimoku_base"] = ichi.ichimoku_base_line()
        df["ichimoku_a"]    = ichi.ichimoku_a()
        df["ichimoku_b"]    = ichi.ichimoku_b()

        # 9) Preparar addplot (cada serie 1-D)
        apds = [
            mpf.make_addplot(df[f"SMA_{sma_short}"], color='cyan'),
            mpf.make_addplot(df[f"SMA_{sma_med}"],   color='orange'),
            mpf.make_addplot(df[f"SMA_{sma_long}"],  color='magenta'),
            mpf.make_addplot(df["ichimoku_conv"], color='lime'),
            mpf.make_addplot(df["ichimoku_base"], color='yellow'),
            mpf.make_addplot(df["ichimoku_a"],    color='green'),
            mpf.make_addplot(df["ichimoku_b"],    color='red'),
            mpf.make_addplot(df["MACD"], panel=1, color='fuchsia'),
            mpf.make_addplot(df["MACD_signal"], panel=1, color='b'),
            mpf.make_addplot(df["MACD_diff"], type='bar', panel=1, color='gray', alpha=0.5),
            mpf.make_addplot(df["RSI"], panel=2, color='yellow'),
        ]

        style_name = 'nightclouds' if 'nightclouds' in mpf.available_styles() else 'yahoo'
        mpf_style = mpf.make_mpf_style(base_mpf_style=style_name, rc={'figure.facecolor':'#222222'})

        outp = f"{output_folder}/{ticker.replace('.','_')}_full_tech.png"
        title = f"{ticker} — Velas + SMA({sma_short},{sma_med},{sma_long}) + Ichimoku + MACD + RSI"

        # 10) Plot
        mpf.plot(
            df,
            type='candle',
            style=mpf_style,
            addplot=apds,
            volume=True,
            panel_ratios=(6,2,2),
            figsize=(16,8),
            title=title,
            tight_layout=True,
            savefig=dict(fname=outp, dpi=150, bbox_inches='tight')
        )

        display(Image(outp))
        print("Guardado:", outp)

    except Exception as e:
        print(f"Error con {ticker}: {repr(e)}")



# CELDA CORREGIDA: quitar 'linewidth' -> usar 'width' en mpf.make_addplot
#!pip install mplfinance ta --quiet

import pandas as pd
import numpy as np
import mplfinance as mpf
from IPython.display import Image, display
from ta.trend import SMAIndicator, MACD, IchimokuIndicator, ADXIndicator
from ta.volume import OnBalanceVolumeIndicator
from ta.momentum import RSIIndicator, StochasticOscillator
from ta.trend import CCIIndicator
import os
os.makedirs(output_folder, exist_ok=True)

# parámetros
sma_short, sma_med, sma_long = 21, 55, 200
rsi_window = 14
stoch_window, stoch_smooth = 14, 3
cci_window = 20
adx_window = 14

def flatten_columns_if_multiindex(df):
    if not isinstance(df.columns, pd.MultiIndex):
        df.columns = [str(c) for c in df.columns]
        return df
    lvl_values = [set(df.columns.get_level_values(i)) for i in range(df.columns.nlevels)]
    needed = {'Open','High','Low','Close','Volume'}
    for i, s in enumerate(lvl_values):
        if needed.issubset(s):
            df.columns = df.columns.get_level_values(i)
            return df
    last = df.columns.get_level_values(-1)
    if needed.issubset(set(last)):
        df.columns = last
        return df
    df.columns = ['_'.join([str(x) for x in col if x is not None and str(x) != '']) for col in df.columns]
    return df

def find_and_map_ohlcv_names(df):
    cols = list(df.columns)
    cols_lower = {c:c.lower() for c in cols}
    mapping = {}
    for wanted in ['open','high','low','close','volume']:
        found = None
        for c, cl in cols_lower.items():
            if cl == wanted:
                found = c; break
        if found is None:
            for c, cl in cols_lower.items():
                if wanted in cl:
                    found = c; break
        if found:
            mapping[found] = wanted.capitalize()
    if mapping:
        df = df.rename(columns=mapping)
    return df

def to_1d_series_safe(val, index):
    arr = np.asarray(val)
    arr = arr.ravel()
    s = pd.Series(arr, index=index)
    s = pd.to_numeric(s.astype(object), errors='coerce').astype(float)
    return s

# Recorremos data_dict
for ticker, df in list(data_dict.items()):
    try:
        print("Procesando:", ticker)
        if df is None or df.empty:
            print("  -> sin datos, salto.")
            continue

        df = df.copy()
        df.index = pd.to_datetime(df.index)
        df.sort_index(inplace=True)

        # Normalizar nombres
        df = flatten_columns_if_multiindex(df)
        df = find_and_map_ohlcv_names(df)

        # Verificar OHLCV
        required = ['Open','High','Low','Close','Volume']
        missing = [c for c in required if c not in df.columns]
        if missing:
            print(f"  -> Faltan columnas OHLCV: {missing}")
            print("  -> Columnas disponibles:", list(df.columns)[:30])
            display(df.head(3))
            print("  -> Saltando ticker.")
            continue

        # Forzar 1-D floats
        for c in required:
            df[c] = to_1d_series_safe(df[c], df.index)

        # Drop NA y checks
        before = len(df)
        df.dropna(subset=['Open','High','Low','Close'], inplace=True)
        after = len(df)
        if after == 0:
            print("  -> no quedan filas tras dropna(OHLC), salto.")
            continue
        if after < before:
            print(f"  -> eliminadas {before-after} filas por OHLC incompleto. Restan {after} filas")

        df[['Open','High','Low','Close','Volume']] = df[['Open','High','Low','Close','Volume']].astype(float)

        # Series 1-D
        close = pd.Series(df['Close'].values.ravel(), index=df.index, name='Close')
        high  = pd.Series(df['High'].values.ravel(), index=df.index, name='High')
        low   = pd.Series(df['Low'].values.ravel(), index=df.index, name='Low')
        vol   = pd.Series(df['Volume'].values.ravel(), index=df.index, name='Volume')

        # Indicadores
        df[f"SMA_{sma_short}"] = SMAIndicator(close, window=sma_short).sma_indicator()
        df[f"SMA_{sma_med}"]   = SMAIndicator(close, window=sma_med).sma_indicator()
        df[f"SMA_{sma_long}"]  = SMAIndicator(close, window=sma_long).sma_indicator()

        macd = MACD(close, window_slow=26, window_fast=12, window_sign=9)
        df["MACD"]        = macd.macd()
        df["MACD_signal"] = macd.macd_signal()
        df["MACD_diff"]   = macd.macd_diff()

        df["RSI"] = RSIIndicator(close, window=rsi_window).rsi()

        # 1) Calcular Tenkan, Kijun, SenkouA, SenkouB y Chikou manualmente (control total)
        tenkan = (high.rolling(window=9).max() + low.rolling(window=9).min()) / 2
        kijun  = (high.rolling(window=26).max() + low.rolling(window=26).min()) / 2
        # Senkou A y B se proyectan hacia el futuro (lead) típicamente 26 periodos
        senkou_a = ((tenkan + kijun) / 2).shift(26)
        senkou_b = ((high.rolling(window=52).max() + low.rolling(window=52).min()) / 2).shift(26)
        chikou = close.shift(-26)

        # Guardar en df para usar en addplot / leyenda si quieres
        df["ICH_Tenkan"] = tenkan
        df["ICH_Kijun"]  = kijun
        df["ICH_Senkou_A"] = senkou_a
        df["ICH_Senkou_B"] = senkou_b
        df["ICH_Chikou"] = chikou

        stoch = StochasticOscillator(high=high, low=low, close=close, window=stoch_window, smooth_window=stoch_smooth)
        df["STOCH_k"] = stoch.stoch()
        df["STOCH_d"] = stoch.stoch_signal()

        df["CCI"] = CCIIndicator(high=high, low=low, close=close, window=cci_window).cci()

        # ADX y OBV
        df["ADX"] = ADXIndicator(high=high, low=low, close=close, window=adx_window).adx()
        df["OBV"] = OnBalanceVolumeIndicator(close=close, volume=vol).on_balance_volume()

        # Preparar addplots — usar 'width' en lugar de 'linewidth'
        apds = [
            mpf.make_addplot(df[f"SMA_{sma_short}"], color='#EDF67D',  width=0.8, panel=0, label=f"SMA {sma_short}"),
            mpf.make_addplot(df[f"SMA_{sma_med}"],   color='#CA7DF9', width=0.8, panel=0, label=f"SMA {sma_med}"),
            mpf.make_addplot(df[f"SMA_{sma_long}"],  color='#40F7DF',width=0.8, panel=0, label=f"SMA {sma_long}"),
            mpf.make_addplot(df["ICH_Tenkan"], panel=0, color='green', width=0.2, label='Tenkan'),
            mpf.make_addplot(df["ICH_Kijun"],  panel=0, color='lightcoral', width=0.2, label='Kijun'),
            mpf.make_addplot(df["ICH_Senkou_A"], panel=0, color='lightgreen', width=1.0, label='Senkou A'),
            mpf.make_addplot(df["ICH_Senkou_B"], panel=0, color='red', width=1.0, label='Senkou B'),

            mpf.make_addplot(df["MACD"],        panel=1, color='fuchsia', width=0.9, label='MACD'),
            mpf.make_addplot(df["MACD_signal"], panel=1, color='gold',    width=0.9, label='Signal'),
            mpf.make_addplot(df["MACD_diff"],   panel=1, type='bar', color='gray', alpha=0.5, ylabel='MACD hist'),

            mpf.make_addplot(df["RSI"], panel=2, color='yellow', width=0.9, label='RSI'),
            mpf.make_addplot(df["ADX"], panel=2, color='lime',   width=0.9, label='ADX'),

            mpf.make_addplot(df["STOCH_k"], panel=3, color='lime', width=0.9, label='Stoch %K'),
            mpf.make_addplot(df["STOCH_d"], panel=3, color='magenta', width=0.9, label='Stoch %D'),
            mpf.make_addplot(df["CCI"],     panel=3, color='purple', width=0.9, label='CCI'),

            mpf.make_addplot(df["OBV"], panel=4, color='silver', ylabel='OBV'),
        ]

        style_name = 'nightclouds' if 'nightclouds' in mpf.available_styles() else 'yahoo'
        mpf_style = mpf.make_mpf_style(base_mpf_style=style_name, rc={'figure.facecolor':'#222222'})

        outp = f"{output_folder}/{ticker.replace('.','_')}_full_with_adx_obv.png"
        title = f"{ticker} — Candles + SMAs + Ichimoku (nube) + MACD + RSI+ADX + Stoch+CCI + OBV"

        # Plot
        fig, axes = mpf.plot(
            df,
            type='candle',
            style=mpf_style,
            addplot=apds,          # tus addplots (sin Ichimoku si vas a pintar manual)
            volume=True,
            panel_ratios=(6,2,2,2,2),
            figsize=(16,11),
            title=title,
            tight_layout=True,
            returnfig=True
        )
        ax_price = axes[0]

        # 3) Sombrear la nube sólo en tramos válidos (ambas series no-NaN)
        sa = df["ICH_Senkou_A"]
        sb = df["ICH_Senkou_B"]
        # máscara donde ambas son válidas
        mask_valid = (~sa.isna()) & (~sb.isna())

        if mask_valid.any():
            # pintar verde donde A >= B
            ax_price.fill_between(df.index,
                                  sa, sb,
                                  where=(mask_valid & (sa >= sb)),
                                  interpolate=True,
                                  color='lightgreen', alpha=0.18)
            # pintar rojo donde A < B
            ax_price.fill_between(df.index,
                                  sa, sb,
                                  where=(mask_valid & (sa < sb)),
                                  interpolate=True,
                                  color='lightcoral', alpha=0.18)
        # Leyenda
        try:
            handles, labels = ax_price.get_legend_handles_labels()
            if handles:
                ax_price.legend(handles, labels, loc='upper left', fontsize='small')
        except Exception:
            pass

        # Guardar y mostrar
        fig.savefig(outp, dpi=150, bbox_inches='tight')
        display(Image(outp))
        print("Guardado:", outp)
        import matplotlib.pyplot as plt
        plt.close(fig)

    except Exception as e:
        print(f"Error con {ticker}: {repr(e)}")

